resolver: lts-14.27
compiler: ghc-8.6.5

packages:
- .

extra-deps:
- text-1.2.4.0
- bytestring-0.10.12.0
- aeson-1.4.6.0
- http-types-0.12
- http-client-0.6.4
- http-client-tls-0.3.5
- time-1.8.0.4
- directory-1.3.6.1
- process-1.6.10.0
- binary-0.8.8.0
- array-0.5.4.0
- containers-0.6.4.1
- deepseq-1.4.4.0
- filepath-1.4.2.1
- mtl-2.2.2
- parsec-3.1.14.0
- stm-2.5.0.0
- transformers-0.5.6.2
- unix-2.7.2.2
